version: "3.0"
services:
  node:
    image: node:12.16.0-slim
    env_file: .env
    working_dir: /app
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on: 
      - mongo
    links:
      - "mongo:{$MONGO_HOST}"

  mongo:
    image: mongo
    restart: always

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on: 
      - mongo
